KareAjansProject/KareAjans.MVC/Controllers/MankenController.cs
using KareAjans.BLL.AbstractService;
using KareAjans.BLL.Service;
using KareAjans.Entity.Enums;
using KareAjans.MVC.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KareAjans.MVC.Controllers
{
    public class MankenController : Controller
    {
        private readonly IMankenService _mankenService;
        private readonly IFotografService _fotografService;

        public MankenController(IMankenService mankenService,IFotografService fotografService)
        {
            _mankenService = mankenService;
            _fotografService = fotografService;
        }
        [Authorize]
        public IActionResult Index(int? yas,Cinsiyet? cinsiyet )
        {
            MankenFotografVM mankenFotografVM = new MankenFotografVM();
            if (yas !=null)
            {
                mankenFotografVM.Mankenler = _mankenService.GetAllManken().Where(x=>x.DogumTarihi.Year>=2005).ToList();
            }
            if (cinsiyet == KareAjans.Entity.Enums.Cinsiyet.Erkek)
            {
                mankenFotografVM.Mankenler = _mankenService.GetAllManken().Where(x => x.Cinsiyet== KareAjans.Entity.Enums.Cinsiyet.Erkek).ToList();
            }
            if (cinsiyet == KareAjans.Entity.Enums.Cinsiyet.Kadın)
            {
                mankenFotografVM.Mankenler = _mankenService.GetAllManken().Where(x => x.Cinsiyet == KareAjans.Entity.Enums.Cinsiyet.Kadın).ToList();
            }
            if(yas==null && cinsiyet==null)
            {
                mankenFotografVM.Mankenler = _mankenService.GetAllManken().ToList();
            }

            mankenFotografVM.Fotograflar = _fotografService.GetAllFotograf().ToList();

            return View(mankenFotografVM);
        }
        [Authorize]
        public IActionResult Details(int id)
        {
            MankenFotografVM mankenFotografVM = new MankenFotografVM();
            mankenFotografVM.Mankenler = _mankenService.GetAllManken().ToList();
            mankenFotografVM.Fotograflar = _fotografService.GetAllFotograf().ToList();
            ViewBag.Manken = _mankenService.FindManken(id);

            return View(mankenFotografVM);
            
        }
    }
}

KareAjansProject/KareAjans.MVC/Controllers/UserController.cs
using KareAjans.BLL.AbstractService;
using KareAjans.Entity.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace KareAjans.MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IOrderService _orderService;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, IOrderService orderService, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _orderService = orderService;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Profile()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            return View(user);
        }

        public IActionResult MyOrganizasyon(string id)
        {
            List<Order> orders = new List<Order>();

            if(_orderService.GetAllOrders().Where(x=>x.UserId==id).FirstOrDefault() != null)
            {
                foreach (var item in _orderService.GetAllOrders().ToList())
                {
                    if (item.UserId==id)
                    {

                        orders.Add(item);

                    }
                }
            }
          
            return View(orders);
        }

        public async Task<IActionResult> Logout()
        {
            
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        
    }
}

KareAjansProject/KareAjans.MVC/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/admin-template/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="Admin/Home">Start Bootstrap</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
           
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="/User/Logout">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="/Admin/Home">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" href="/Admin/Manken">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Manken
                        </a>
                        <a class="nav-link" href="/Admin/Organizasyon/OrganizasyonIndex">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Organizasyonlar
                        </a><a class="nav-link" href="/Admin/Organizasyon">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Organizasyon Siparişleri
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            @*<footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Your Website 2023</div>
            <div>
            <a href="#">Privacy Policy</a>
            &middot;
            <a href="#">Terms &amp; Conditions</a>
            </div>
            </div>
            </div>
            </footer>*@
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/admin-template/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/admin-template/assets/demo/chart-area-demo.js"></script>
    <script src="~/admin-template/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/admin-template/js/datatables-simple-demo.js"></script>
</body>
</html>

KareAjansProject/KareAjans.MVC/Views/Shared/_FooterPartial.cshtml
<footer class="border-top footer text-muted " >
    <div class="container" >
        <span > - KareAjans.MVC - </span>
    </div>
</footer>

KareAjansProject/KareAjans.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/model-template/assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/model-template/css/styles.css" rel="stylesheet" />
    <style>
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: white;
            color: white;
            text-align: center;
        }
    </style>
</head>
<body>
    <!-- Navigation-->
    @Html.Partial("_NavbarPartial")
    <!-- Header-->

    <!-- Section-->
    <section class="py-1">
        <div class="container px-4 px-lg-5 mt-5">
           @RenderBody()
        </div>
    </section>
    <!-- Footer-->
    @Html.Partial("_FooterPartial")
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/model-template/js/scripts.js"></script>
</body>
</html>

KareAjansProject/KareAjans.MVC/Views/Shared/_MuhasebeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Muhasebe</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/admin-template/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="/Muhasebe/Home/Index">Start Bootstrap</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
      
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="User/Logout">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="/Muhasebe/Home">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" href="/Muhasebe/Manken">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Manken
                        </a>
                        <a class="nav-link" href="/Muhasebe/Organizasyon">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Organizasyon
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/admin-template/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/admin-template/assets/demo/chart-area-demo.js"></script>
    <script src="~/admin-template/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/admin-template/js/datatables-simple-demo.js"></script>
</body>
</html>
       

KareAjansProject/KareAjans.MVC/Views/Shared/_NavbarPartial.cshtml
@{
    var sepet = Kareajans.MVC.Utils.SessionHelper.GetProductFromJson<Kareajans.Common.Cart>(Context.Session, "organizasyon");

}

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kare Ajans</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Hakkimizda">Hakkımızda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Referanslar">Referanslar</a>
                </li>
                <li class="nav-item">
                    <div class="btn-group">
                        <button type="button" class="btn" data-bs-toggle="dropdown" aria-expanded="false">
                            Mankenler
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Manken" asp-action="Index" >Mankenler</a></li>
                            <li><a class="dropdown-item" asp-controller="Manken" asp-action="Index" asp-route-cinsiyet="Kadın"  >Kadın Mankenler</a></li>
                            <li><a class="dropdown-item" asp-controller="Manken" asp-action="Index" asp-route-cinsiyet="Erkek">Erkek Mankenler</a></li>
                            <li><a class="dropdown-item" asp-controller="Manken" asp-action="Index" asp-route-yas="18">Çocuk Mankenler</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Organizasyonlar">Organizasyonlar</a>
                </li>
            </ul>
        </div>

        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a asp-action="MyOrganization" asp-controller="Home" class="btn btn-outline-dark me-md-2" type="submit">
                        <i class="bi-cart-fill me-1"></i>
                        Cart

                        @if (sepet != null)
                        {

                            <span class="badge bg-dark text-white ms-1 rounded-pill">@sepet._myCart.Count</span>
                        }
                        else
                        {
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        }

                    </a>
                </li>
                <li class="nav-item">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="dropdown">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @User.Identity.Name
                            </a>
                            @if (User.IsInRole("Admin"))
                            {
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="/admin/home/index">Admin Sayfası</a></li>
                                    <li><a class="dropdown-item" asp-action="Logout" asp-controller="User">Logout</a></li>
                                </ul>
                            }
                            @if (User.IsInRole("Model"))
                            {
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="Model" asp-controller="Manken" asp-action="GetManken" asp-route-id=@TempData["MankenId"]>Profil </a></li>
                                    <li><a class="dropdown-item" asp-action="Logout" asp-controller="User">Logout</a></li>
                                </ul>
                            }
                            @if (User.IsInRole("Muhasebe"))
                            {
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-action="Profile" asp-controller="User">Profil</a></li>
                                    <li><a class="dropdown-item" asp-action="Logout" asp-controller="User">Logout</a></li>
                                </ul>
                            }
                            else
                            {
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-action="Profile" asp-controller="User">Profil</a></li>
                                    <li><a class="dropdown-item" asp-action="Logout" asp-controller="User">Logout</a></li>

                                </ul>
                            }
                        </div>
                    }
                    else
                    {
                        <a asp-action="Login" asp-controller="Home" class="btn btn-primary me-md-2">Login</a>
                        <a asp-action="Register" asp-controller="Home" class="btn btn-outline-primary">Register</a>
                    }
                </li>
            </ul>
        </div>
    </div>
</nav>