KareAjansProject/KareAjans.MVC/Areas/Admin/Controllers/OrganizasyonController.cs
using Kareajans.Common;
using Kareajans.MVC.Utils;
using KareAjans.BLL.AbstractService;
using KareAjans.BLL.Service;
using KareAjans.Entity.Entities;
using KareAjans.Entity.Enums;
using KareAjans.MVC.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KareAjans.MVC.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class OrganizasyonController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IOrderDetailService _orderDetailService;
        private readonly IMankenService _mankenService;
        private readonly IOrganizasyonService _organizasyonService;
        private readonly IOrganizasyonGelirService _organizasyonGelirService;
        private readonly IAdresService _adresService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IOrganizasyonGiderService _organizasyonGiderService;

        public OrganizasyonController(IOrderService orderService, IOrderDetailService orderDetailService,IMankenService mankenService,IOrganizasyonService organizasyonService,IOrganizasyonGiderService organizasyonGiderService,IOrganizasyonGelirService organizasyonGelirService,IAdresService adresService, UserManager<IdentityUser> userManager)
        {
            _orderService = orderService;
            _orderDetailService = orderDetailService;
            _mankenService = mankenService;
            _organizasyonService = organizasyonService;
            _organizasyonGelirService = organizasyonGelirService;
            _adresService = adresService;
            _userManager = userManager;
            _organizasyonGiderService = organizasyonGiderService;
            
        }
        public IActionResult Index()
        {

            return View(_orderService.GetAllOrders().ToList());
        }
        public IActionResult Details(int id)
        {
            var od=_orderDetailService.GetAllOrderDetails();
            List<OrderDetail> ordersDetail = new List<OrderDetail>();

            foreach (var item in od)
            {
                if (item.OrderId==id)
                {
                    ordersDetail.Add(item);
                }

            }

            OrderDetailMankenVM orderDetailMankenVM = new OrderDetailMankenVM();
            orderDetailMankenVM.OrderDetails = ordersDetail;
            orderDetailMankenVM.Mankenler=_mankenService.GetAllManken().ToList();
            orderDetailMankenVM.Orders=_orderService.GetAllOrders().ToList();

            return View(orderDetailMankenVM);
        }
        [HttpPost]
        public IActionResult Details(string adi,string adresacik,string adressehir,DateTime baslangic,DateTime bitis,decimal ogunucreti,decimal konaklamaucreti,decimal gunlukucret,decimal butce,int orderdetailsid)
        {
            _orderService.FindOrder(orderdetailsid).Onaylama = true;


            Adres adres = new Adres();
            adres.AcikAdres = adresacik;
            adres.Sehir = adressehir;
            
            _adresService.CreateAdres(adres);

            Organizasyon organizasyon = new Organizasyon();
            organizasyon.OrganizasyonAdi = adi;
            organizasyon.BaslangicTarihi = baslangic;
            organizasyon.BitisTarihi = bitis;
            organizasyon.AdresId = adres.Id;
            
            _organizasyonService.CreateOrganizasyon(organizasyon);

            OrganizasyonGelir organizasyonGelir = new OrganizasyonGelir();
            organizasyonGelir.Butce = butce;
            organizasyonGelir.OrganizasyonId = organizasyon.Id;
            _organizasyonGelirService.CreateOrganizasyonGelir(organizasyonGelir);

            var a=_orderDetailService.GetAllOrderDetails().Where(x=>x.OrderId==orderdetailsid).ToList();
            var ucuncuKategoriMankenSayisi = 0;
            foreach (var item in a)
            {
                switch (_mankenService.FindManken(item.MankenId).Kategori)
                {
                    case Entity.Enums.MankenKategori.Kategori1:

                        break;
                    case Entity.Enums.MankenKategori.Kategori2:

                        break;
                    case Entity.Enums.MankenKategori.Kategori3:
                        ucuncuKategoriMankenSayisi++;
                        break;

                }
            }

            foreach (var item in _orderDetailService.GetAllOrderDetails())
            {
                if(item.OrderId == orderdetailsid) 
                {
                    OrganizasyonGider organizasyonGider = new OrganizasyonGider();
                    organizasyonGider.OrganizasyonId = organizasyon.Id;
                    organizasyonGider.MankenId= item.MankenId;
                    organizasyonGider.Butce = butce;
                    organizasyonGider.OgunUcreti = 150;

                    if (konaklamaucreti!=0)
                    {
                        organizasyonGider.KonaklamaUcreti = 500;
                    }
                    switch (_mankenService.FindManken(item.MankenId).Kategori)
                    {
                        case Entity.Enums.MankenKategori.Kategori1:
                            organizasyonGider.GunlukUcret = 500;
                            break;
                        case Entity.Enums.MankenKategori.Kategori2:
                            organizasyonGider.GunlukUcret = 1000;
                            break;
                        case Entity.Enums.MankenKategori.Kategori3:
                            organizasyonGider.GunlukUcret = (butce *20)/100;
                            break;

                    }
                    organizasyonGider.KategoriUcMankenSayisi = ucuncuKategoriMankenSayisi;
                    _organizasyonGiderService.CreateOrganizasyonGider(organizasyonGider);

                }

                

            }

            return RedirectToAction("OrganizasyonIndex");
        }

        public IActionResult OrganizasyonIndex()
        {
            return View(_organizasyonService.GetAllOrganizasyon().ToList());
        }

        public IActionResult OrganizasyonDetails(int id)
        {

            var oGider = _organizasyonGiderService.GetAllOrganizasyonGider();
            List<OrganizasyonGider> organizasyonGider = new List<OrganizasyonGider>();

            foreach (var item in oGider)
            {
                if (item.OrganizasyonId == id)
                {
                    organizasyonGider.Add(item);
                }
            }
            OrganizasyonGeliGiderVM organizasyonGeliGiderVM = new OrganizasyonGeliGiderVM();
            organizasyonGeliGiderVM.OrganizasyonGiderleri = organizasyonGider;
            organizasyonGeliGiderVM.Organizasyonlar = _organizasyonService.GetAllOrganizasyon().ToList();
            organizasyonGeliGiderVM.Mankenler = _mankenService.GetAllDeletedManken().ToList();
            organizasyonGeliGiderVM.Adresler = _adresService.GetAllAdres().ToList();

            return View(organizasyonGeliGiderVM);

        }


        public IActionResult OrganizasyonOlustur(string firstName, string lastName, Cinsiyet? gender, AyakkabıNo? shoeSize, GozRengi? eyeColor, SacRengi? hairColor, Beden? bodySize, int age, byte weight, byte height, MankenKategori? professionalDegreeId, string foreignLanguage, bool? ehliyet, bool? sehirDisiCalisma,DateTime baslangic,DateTime bitis)
        {
            var organizasyon = _organizasyonService.GetAllOrganizasyon()
                        .Where(org =>
                            (org.BaslangicTarihi > bitis) ||
                            (org.BitisTarihi < baslangic))
                        .ToList();


            var organizasyonGiderleri = _organizasyonGiderService.GetAllOrganizasyonGider();
            List<Manken> mankenList = new List<Manken>();


            List<Manken> mankens = new List<Manken>();
          
            List<OrganizasyonGider> gider = new List<OrganizasyonGider>();
            mankenList = _mankenService.GetAllManken().ToList();
            
            var a = _mankenService.GetAllManken().ToList();
           

            foreach (var item in organizasyonGiderleri)
            {
                var oId = organizasyon.FirstOrDefault(x => x.Id == item.OrganizasyonId);

                if (oId == null)
                {
                    mankens.AddRange(_mankenService.GetAllManken().Where(x => x.Id == item.MankenId).ToList());
                 
                }

            }
            


            foreach (var manken in mankenList)
            {
                if (mankens.Where(x => x.Id == manken.Id).FirstOrDefault() != null)
                {
                    a.Remove(manken);
                }
            }
            mankenList = a;
            






           //var mankenList = _mankenService.GetAllManken();//to list eklendiğinde Ienumerable liste tipini liste çevirdiğimiz için diğer kriterlerde hata alıyoruz.

            if (!string.IsNullOrEmpty(firstName))
            {
                mankenList = mankenList.Where(x => x.Ad.Contains(firstName)).ToList();
            }

            if (!string.IsNullOrEmpty(lastName))
            {
                mankenList = mankenList.Where(x => x.Soyad.Contains(lastName)).ToList();
            }
            if (gender != null)
            {
                mankenList = mankenList.Where(x => x.Cinsiyet == gender.Value).ToList();
            }
            if (shoeSize.HasValue)
            {
                mankenList = mankenList.Where(x => x.AyakkabıNo == shoeSize.Value).ToList();
            }
            if (eyeColor.HasValue)
            {
                mankenList = mankenList.Where(x => x.GozRengi == eyeColor.Value).ToList();
            }

            if (hairColor.HasValue)
            {
                mankenList = mankenList.Where(x => x.SacRengi == hairColor.Value).ToList();
            }

KareAjansProject/KareAjans.MVC/Areas/Admin/Views/Organizasyon/Details.cshtml
@model OrderDetailMankenVM
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    decimal? toplamGider = 0;
    decimal? ogunUcreti = 0;
    decimal? konaklamaUcreti = 0;
    decimal? gunlukUcret = 0;
    int? id = 0;
}

<div class="container">
    <div class="card-header">
        <div class="d-flex justify-content-between">
            <h5>Organizasyon Detay</h5>
        </div>
        <div>
            <span>Organiasyon ID:<h5>@Model.Orders.Where(x=>x.Id==Model.OrderDetails.Select(x=>x.OrderId).FirstOrDefault()).Select(x=>x.Id).FirstOrDefault()</h5>  </span>
            <br />
            <span>Organiasyon Şehri: <h5>@Model.Orders.Where(x=>x.Id==Model.OrderDetails.Select(x=>x.OrderId).FirstOrDefault()).Select(x=>x.OrganizasyonSehirAdresi).FirstOrDefault()</h5> </span>
            <br />
            <span>Organiasyon Adresi: <h5>@Model.Orders.Where(x=>x.Id==Model.OrderDetails.Select(x=>x.OrderId).FirstOrDefault()).Select(x=>x.OrganizasyonAdresi).FirstOrDefault()</h5> </span>
            <br />
            <span>Organiasyon Başlangıç Tarihi: <h5>@Model.Orders.Where(x=>x.Id==Model.OrderDetails.Select(x=>x.OrderId).FirstOrDefault()).Select(x=>x.BaslangicTarihi).FirstOrDefault().ToString("dd/MM/yyyy")</h5> </span>
            <br />
            <span>Organiasyon Bitiş Tarihi: <h5>@Model.Orders.Where(x=>x.Id==Model.OrderDetails.Select(x=>x.OrderId).FirstOrDefault()).Select(x=>x.BitisTarihi).FirstOrDefault().ToString("dd/MM/yyyy")</h5> </span>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between">
                <h5>Organizasyon Detay</h5>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Adı</th>
                        <th>Soyadı</th>
                        <th>Boy</th>
                        <th>Kilo</th>
                        <th>Kategori</th>
                        <th>Telefon No</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.OrderDetails)
                    {

                        var gunSayisi = (item.Order.BitisTarihi - item.Order.BaslangicTarihi).Days + 1;



                        if (item.Order.OrganizasyonSehirAdresi.ToLower() == "istanbul")
                        {
                            @switch (item.Kategori)
                            {
                                case KareAjans.Entity.Enums.MankenKategori.Kategori1:
                                    ogunUcreti += 150 * gunSayisi;
                                    gunlukUcret += 500 * gunSayisi;

                                    break;

                                case KareAjans.Entity.Enums.MankenKategori.Kategori2:
                                    ogunUcreti += 150 * gunSayisi;
                                    gunlukUcret += 1000 * gunSayisi;

                                    break;

                                case KareAjans.Entity.Enums.MankenKategori.Kategori3:
                                    ogunUcreti += 150 * gunSayisi;

                                    break;

                            }
                        }
                        else
                        {
                            @switch (item.Kategori)
                            {
                                case KareAjans.Entity.Enums.MankenKategori.Kategori1:
                                    ogunUcreti += 150 * gunSayisi*2;
                                    konaklamaUcreti += 500 * gunSayisi;
                                    gunlukUcret += 500 * gunSayisi;

                                    break;

                                case KareAjans.Entity.Enums.MankenKategori.Kategori2:
                                    ogunUcreti += 150 * gunSayisi*2;
                                    konaklamaUcreti += 500 * gunSayisi;
                                    gunlukUcret += 1000 * gunSayisi;

                                    break;

                                case KareAjans.Entity.Enums.MankenKategori.Kategori3:
                                    ogunUcreti += 150 * gunSayisi*2;
                                    konaklamaUcreti += 500 * gunSayisi;

                                    break;

                            }
                        }


                        <tr>
                            <td>@item.Manken.Id</td>
                            <td>@item.Manken.Ad</td>
                            <td>@item.Manken.Soyad</td>
                            <td>@item.Manken.Boy</td>
                            <td>@item.Manken.Kilo</td>
                            <td>@item.Kategori</td>
                            <td>@item.Manken.TelefonNo</td>
                        </tr>
                        toplamGider = ogunUcreti + konaklamaUcreti + gunlukUcret;
                        id = item.OrderId;
                    }
                </tbody>
            </table>

            <h5>Organizasyon Oluşturma</h5>
            <form href="/admin/organizasyon/details" method="post" enctype="multipart/form-data">

                <div class="mb-3">
                    <label class="form-label">Organizasyon Adı</label>
                    <input type="text" style="background-color:white" class="form-control" placeholder="Organizasyon Adı" name="adi">
                </div>


                <div class="mb-3">
                    <label class="form-label">Organizasyon Şehir Adresi</label>
                    <input type="text" style="background-color:white" class="form-control" placeholder="Organizasyon Şehir Adresi" name="adressehir">
                </div>

                <div class="mb-3">
                    <label class="form-label">Organizasyon Açık Adresi</label>
                    <input type="text" style="background-color:white" class="form-control" placeholder="Organizasyon Açık Adresi" name="adresacik">
                </div>

                <div class="mb-3">
                    <label class="form-label">Organizasyon Başlangıç Tarihi</label>
                    <input type="date" style="background-color:white" class="form-control" placeholder="Organizasyon Başlangıç Tarihi" name="baslangic">
                </div>

                <div class="mb-3">
                    <label class="form-label">Organizasyon Bitiş Tarihi</label>
                    <input type="date" style="background-color:white" class="form-control" placeholder="Organizasyon Bitiş Tarihi" name="bitis">
                </div>

                <div class="mb-3">
                    <label class="form-label">Organizasyon Öğün Gideri:</label>
                    <input type="number" style="background-color:white" class="form-control" value=@ogunUcreti name="ogunucreti" readonly>
                </div>

                <div class="mb-3">
                    <label class="form-label">Organizasyon Konaklama Gideri:</label>
                    <input type="number" style="background-color:white" class="form-control" value=@konaklamaUcreti name="konaklamaucreti" readonly>
                </div>

                <div class="mb-3">
                    <label class="form-label">Organizasyon Günlük Ücret Gideri(3. Kategori Mankenler Hariç.):</label>
                    <input type="number" style="background-color:white" class="form-control" value=@gunlukUcret name="gunlukucret" readonly>
                </div>

                <div class="mb-3">
                    <label class="form-label">Organizasyon Gideri(3. Kategori Mankenin Alacağı Ücreti Hariç): @toplamGider TL.</label>
                    <br />
                    <label class="form-label">3. Kategori Manken Sayısına ve Ücretine Göre Bir Fiyat Belirleyin:</label>
                    <input type="number" style="background-color:white" class="form-control" placeholder="Organizasyon Fiyatı" name="butce">
                </div>

                <div>
                    <input type="hidden" style="background-color:white" class="form-control" value=@id name="orderdetailsid" readonly>
                </div>

                <input type="submit" value="Gönder" />
            </form>
        </div>
    </div>
</div>

KareAjansProject/KareAjans.MVC/Areas/Admin/Views/Organizasyon/MyOrganization.cshtml
@model Kareajans.Common.Cart
@{
    ViewData["Title"] = "MyOrganization";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-9">
        <table class="table">
            <thead>
                <tr>
                    <th>Manken Adı</th>
                    <th>Manken Soyadı</th>
                    <th>Manken Boy</th>
                    <th>Manken Kilo</th>
                    <th>Kategorisi</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model._myCart.Values)
                {

                    <tr>
                        <td>@item.MankenAdi</td>
                        <td>@item.MankenSoyadi</td>
                        <td>@item.MankenBoyu</td>
                        <td>@item.MankenKilosu</td>
                        <td>@item.Kategori</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h3>Tarih Aralığı: </h3><!--Organizasyonla modelleri bir view ypaıp tarihi çekmem lazım.-->

                <form asp-action="CompleteOrganization" asp-controller="Organizasyon" method="get">
                    <label class="form-label">Organizasyonun Yapılacağı Şehir</label>
                    <input type="text" name="sehir" />
                    <label class="form-label">Organizasyonun Yapılacağı Açık Adres</label>
                    <input type="text" name="adres" />
                    <label class="form-label">Organizasyonun Yapılacağı Başlangıç Tarihi</label>
                    <input type="date" name="baslangic" />
                    <label class="form-label">Organizasyonun Yapılacağı Bitiş Tarihi</label>
                    <input type="date" name="bitis" />
                    <br />
                    <br />
                    <input type="submit" value="Gönder" />
                </form>

            </div>
        </div>
    </div>

KareAjansProject/KareAjans.MVC/Areas/Admin/Views/Organizasyon/OrganizasyonOlustur.cshtml
@model List<Manken>
@{
    var sepet = Kareajans.MVC.Utils.SessionHelper.GetProductFromJson<Kareajans.Common.Cart>(Context.Session, "organizasyon");
    ViewData["Title"] = "OrganizasyonOlustur";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="card" >
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a asp-action="MyOrganization" asp-controller="Organizasyon" class="btn btn-outline-dark me-md-2" type="submit">
            <i class="bi-cart-fill me-1"></i>
            Cart

            @if (sepet != null)
            {

                <span class="badge bg-dark text-white ms-1 rounded-pill">@sepet._myCart.Count</span>
            }
            else
            {
                <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
            }

        </a>
    </div>

    


    <form class="form-horizontal" asp-action="OrganizasyonOlustur" asp-controller="Organizasyon" method="get">

        <div class="card-body">
            <div class="card-title"><h2>Manken Arama / Atama</h2></div>
            <div class="row">

                <div class="col-md-4">

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">İsim:</label>
                        <div class="col-md-9">
                            <input type="text" name="firstName" class="form-control" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Soyisim:</label>
                        <div class="col-md-9">
                            <input type="text" name="lastName" class="form-control" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Cinsiyet:</label>
                        <div class="col-md-9">
                            <select class="select2 form-control custom-select" style="width: 100%; height:36px;" name="gender" asp-items="Html.GetEnumSelectList<KareAjans.Entity.Enums.Cinsiyet>()">
                                <option value="">Hepsi</option>
                            </select>
                        </div>
                    </div>


                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Derecesi:</label>
                        <div class="col-md-9">
                            <select class="select2 form-control custom-select" style="width: 100%; height:36px;" name="professionalDegreeId" asp-items="Html.GetEnumSelectList<KareAjans.Entity.Enums.MankenKategori>()">
                                <option value="">Hepsi</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row m-t-20">
                        <label class="col-sm-3 text-right control-label col-form-label">Yaş:</label>
                        <div class="col-md-9">
                            <input type="number" name="age" class="form-control" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Kilo:</label>
                        <div class="col-md-9">
                            <input type="number" name="weight" class="form-control" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Boy:</label>
                        <div class="col-md-9">
                            <input type="number" name="height" class="form-control" />
                        </div>
                    </div>

                </div>
                <div class="col-md-4">

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Ayakkabı Numarası:</label>
                        <div class="col-md-9">
                            <select class="select2 form-control custom-select" style="width: 100%; height:36px;" name="shoeSize" asp-items="Html.GetEnumSelectList<KareAjans.Entity.Enums.AyakkabıNo>()">
                                <option value="">Hepsi</option>
                            </select>
                        </div>

                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Göz Rengi:</label>
                        <div class="col-md-9">
                            <select class="select2 form-control custom-select" style="width: 100%; height:36px;" name="eyeColor" asp-items="Html.GetEnumSelectList<KareAjans.Entity.Enums.GozRengi>()">
                                <option value="">Hepsi</option>
                            </select>
                        </div>

                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Saç Rengi:</label>
                        <div class="col-md-9">
                            <select class="select2 form-control custom-select" style="width: 100%; height:36px;" name="hairColor" asp-items="Html.GetEnumSelectList<KareAjans.Entity.Enums.SacRengi>()">
                                <option value="">Hepsi</option>
                            </select>
                        </div>

                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Beden:</label>
                        <div class="col-md-9">
                            <select class="select2 form-control custom-select" style="width: 100%; height:36px;" name="bodySize" asp-items="Html.GetEnumSelectList<KareAjans.Entity.Enums.Beden>()">
                                <option value="">Hepsi</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Sürücü Belgesi:</label>
                        <div class="col-md-9">
                            <select class="select2 form-control custom-select" style="width: 100%; height:36px;" name="ehliyet">
                                <option value="">Hepsi</option>
                                <option value="true">Evet</option>
                                <option value="false">Hayır</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Şehir dışı çalışma:</label>
                        <div class="col-md-9">
                            <select class="select2 form-control custom-select" style="width: 100%; height:36px;" name="sehirDisiCalisma">
                                <option value="">Hepsi</option>
                                <option value="true">Evet</option>
                                <option value="false">Hayır</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 text-right control-label col-form-label">Yabancı Dil:</label>
                        <div class="col-md-9">
                            <input name="foreignLanguage" class="form-control" />
                        </div>
                    </div>

                </div>

                
                    <div class="mb-3">
                        <label class="form-label">Organizasyon Başlangıç Tarihi</label>
                        <input type="date" style="background-color:white" class="form-control" placeholder="Organizasyon Başlangıç Tarihi" name="baslangic">
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Organizasyon Bitiş Tarihi</label>
                        <input type="date" style="background-color:white" class="form-control" placeholder="Organizasyon Bitiş Tarihi" name="bitis">
                    </div>

                <div class="border-top">
                    <div class="form-group row">
                        <div class="card-body">
                            <input type="submit" value="Ara" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between">
                <h5>Manken Listesi</h5>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Manken Id</th>
                        <th>Manken Adı</th>
                        <th>Manken Soyadı</th>
                        <th>Boy</th>
                        <th>Kilo</th>
                        <th>Kategori</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Ad</td>
                            <td>@item.Soyad</td>
                            <td>@item.Boy</td>
                            <td>@item.Kilo</td>
                            <td>@item.Kategori</td>
                            <td>
                                <a href ="/Admin/Organizasyon/AddToOrganization/@item.Id" class="btn btn-primary btn-sm">Organizasyona Ekle</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>